### ISSUE TITLE
option to suppress notifications

### ISSUE THREAD

**Issue by Spown** [nickdodd79/vscode-gulptasks#10]
Please add an option to disable ``"Gulp Tasks: The task 'foo' has completed successfully."`` It is perfectly fine to assume if nothing did go wrong - there is nothing to report. Only An error is of an interest. Constantly closing the same non-informative notifications is not very productive.

Thank you.

**Comment by nickdodd79** [comment]
Hi @Spown 

Thanks for the suggestion. You can find these in the new v1.1.0 release. There are settings to control executed, terminated and restarted notifications.

Nick.

**Comment by Spown** [comment]
Thank you.

**Comment by mfreeman-xtivia** [comment]
A favor---can you tell me what setting I would use to disable these notifications? thanks

**Comment by Spown** [comment]
@mfreeman-xtivia if you go to the extension page in VSCode and then to the Contributions tab you will see everything that the said extension adds to the program.

```
gulptasks.notifications.executed | Whether to show notifications for successfully executed tasks.
gulptasks.notifications.terminated | Whether to show notifications for terminated tasks.
gulptasks.notifications.restarted | Whether to show notifications for restarted tasks.
```

@nickdodd79 I think a proper Readme wouldn't harm...

**Comment by nickdodd79** [comment]
@mfreeman-xtivia + @Spown,
The readme has been updated to detail the settings available for the extension.
