### ISSUE TITLE
Execute a task with double click

### ISSUE THREAD

**Issue by Spown** [nickdodd79/vscode-gulptasks#11]
and/or with enter. Thank you.

**Comment by nickdodd79** [comment]
Not done much with keyboard or mouse events in vscode yet, so will need to brush up on that before this request is in place. Watch this space.

**Comment by nickdodd79** [comment]
This request won't be possible just yet due to restrictions with the tree provider offered by vscode. 

Currently it only allows either single or double click events, but not both. I have raised a feature request with the vscode team to provide more event handlers, so we will need to wait on them.

**Comment by nickdodd79** [comment]
The vscode team have said they are looking to get double click handling out in a not-too-far-in-the-future release. As soon as it is available, I will be adding the ability to execute a task using double clicks.

**Comment by nickdodd79** [comment]
Hi @Spown 

Double click has now been added to v1.2.0. Instead of waiting for vscode to natively support double click, I have used some timer trickery to make it possible.

Nick.

**Comment by nickdodd79** [comment]
Hey @Spown 

Glad you like the solution :-) Thanks for reminding me of the interval output - yep, used it for debugging and shouldn't be in there. I've removed it and will push it in the next release.

As this feature is now available, I'm gonna close this issue. I was hoping some new handling would be in the recent 1.25.0 release of vscode, but it looks like we will be awaiting a bit longer. Once it is in there, I will make the coding change, which should be seamless from a user perspective.

Nick.
