### ISSUE TITLE
Some legacy settings have been detected that should be migrated.

### ISSUE THREAD

**Issue by Spown** [nickdodd79/vscode-gulptasks#12]
I get this warning every time VSC is started even when I have no ``gulptasks.*`` settings whatsoever.
```
Gulp Tasks: Some legacy settings have been detected that should be migrated.
Only the 'gulptasks.pattern' and 'gulptasks.filters' settings should used - all others will removed in a future release.
```
Thnx.

**Comment by nickdodd79** [comment]
Hi @Spown 

I forgot to revisit that bit before releasing v1 so thanks for the reminder. In v1.1.1, the legacy settings are no longer included with default values. So only where you have overridden the defaults will that message appear.

Nick.

**Comment by nickdodd79** [comment]
Hopefully the change addressed your issue. Can this be closed?

**Comment by Spown** [comment]
I suppose... thank you
