### ISSUE TITLE
Errorlog

### ISSUE THREAD

**Issue by Roxas92** [nickdodd79/vscode-gulptasks#14]
I just moved from Atom to VSCode und discovered that there is no errorlog or message when my gulp task could not be executed.

In the atom extension I had this windows/log:
![image](https://user-images.githubusercontent.com/7781761/42632723-6c857040-85de-11e8-9c02-ffe38992ae56.png)

Am I missing something or is that just not a part of vscode-gulptasks? If not, I'd like to request this feature.

**Comment by nickdodd79** [comment]
Hi @Roxas92 

All logs and messages emitted by gulp should be displayed in the Output console under the Gulp Tasks channel. You can access the output via the View > Integrated Terminal menu. There is an Output tab and then a dropdown to select the channel.

Here is an example of what you should see (colorizing is unfortunately not provided by vscode yet in this window).
![image](https://user-images.githubusercontent.com/28779139/42655422-86f734dc-865f-11e8-986a-ca994e334a3d.png)

Nick.

**Comment by nickdodd79** [comment]
Hi @Roxas92

I assume this issue is all resolved so will now close it.

Nick.
