### ISSUE TITLE
Q: Adding custom gulp tasks

### ISSUE THREAD

**Issue by mt-webdev** [nickdodd79/vscode-gulptasks#19]
Is it possible to add a gulp task which is not existing inside the gulpfile itself but in a spearate JS file -> like Drag'n'Drop behavior?

**Comment by nickdodd79** [comment]
Hey @mt-webdev 

You can't drag and drop onto the extension. It reads all the gulp*.js files in the workspace. Is the separate file you mention outside the workspace? You can have multiple gulp files scattered throughout your project and the extension will find them (as long as your settings don't exclude them).

Nick.
