### ISSUE TITLE
config location / extraneous gulp files found

### ISSUE THREAD

**Issue by monkunashi** [nickdodd79/vscode-gulptasks#2]
i see node_modules is ignored during autodetection. I believe bower_components should also be ignored. also, I believe it should check the root directory of the workspace FIRST and then search subdirs if a gulpfile isn't found in the root

**Comment by nickdodd79** [comment]
Hi @monkunashi,

You make a valid point that the workspace root should be checked first and returned if found to ensure the most efficient load times (as most gulpfile.js instances will likely be at the root). On a side note, I am in the process of rewriting the extension slightly, which will also include loading multiple gulp files should projects use both a root and nested.

I have also updated the exclude list to not load anything in bower_components.

A new 0.0.6 version is available with these changes.

Nick.
