### ISSUE TITLE
support gulpfile.ts

### ISSUE THREAD

**Issue by simpert** [nickdodd79/vscode-gulptasks#23]
I use `typescript` and therefore my gulp files are `gulpfile.ts` rather then `gulpfile.js`.

*Gulp* supports typescript out of the box.
As long as `ts-node` package has been installed, `gulp taskName` with load `taskName` from the `typescript` file via `ts-node` by auto registering with `gulp --register/ts-node`.

Please support typescript files in extension. I changed the glob to use `.ts` but it doesn't work.

**Comment by nickdodd79** [comment]
Hi @simpert 

Great suggestion. I'll see what I can do.

Nick.

**Comment by nickdodd79** [comment]
Hi @simpert 

I have added a capability that will now let you run a ts gulp file. If you do the following you should be able get your tasks to display and execute:

1. Go to **File** > **Preferences** > **Settings**.
2. Search for `gulptasks`.
3. Set the pattern as `**/gulpfile*.+(js|ts)`.
4. Add `--register/ts-node` to the args array.

Let me know if you have any issues.
