### ISSUE TITLE
Display output automatically

### ISSUE THREAD

**Issue by kAlvaro** [nickdodd79/vscode-gulptasks#24]
It took me a while to figure out that the extension can actually display task output because the corresponding pane is not displayed automatically. I need to manually display the *Output* panel and then select *Gulp Tasks* in the drop-down.

It'd be nice if that could happen automatically.

**Comment by nickdodd79** [comment]
Hi @kAlvaro 

This will be a simple change. There is a capability on the output channel to 'preserveFocus'.

It is set to not show the output - mainly from an annoyance perspective. I will add a setting that will allow you to specify whether it should focus on the output or not.

New release coming soon with some other stuff and I'll include this.

Nick.

**Comment by kAlvaro** [comment]
Pretty good news, thank you.

I'm not very familiar with Gulp yet so this may be a silly idea but... Would it make sense to implement three values for such setting?

- `always`: show *Output* pane when task starts running
- `auto`: show *Output* pane when task prints output
- `never`: do not show *Output* pane

**Comment by nickdodd79** [comment]
I think that'll work - certainly opens more up options than just a true/false alternative.

**Comment by kAlvaro** [comment]
Sorry for flooding the ticket but perhaps there's room for a fourth value like `onError`, that would trigger whenever the task fails. I presume Gulp returns a non-zero code in such case (you'll know better than me because the extension already handles that anyway). I believe that whether something is printed to _stderr_ is not necessarily an indicator of failure.

**Comment by nickdodd79** [comment]
Yep that works well. I've added when a task starts, completes and errors. Every time a message is emitted when a task is in progress. And then the never option.

**Comment by stone821** [comment]
I like this feature, too. When do you release the newest version?

At the moment, I open the Output panel, run a gulp task, then don't output anything in the panel.


Thanks for your hard work.

**Comment by nickdodd79** [comment]
Hi @stone821 

I have put this in place now. It highlighted a slight misalignment with output messages and using gulp.watch, which I have attempted to fix - just testing.

I plan on releasing v1.3.0 over the next few days.

Nick.

**Comment by nickdodd79** [comment]
After some testing I couldn't seem to break anything so published. You can now find a new configuration setting to control the output displaying in v1.3.0.

**Comment by kAlvaro** [comment]
Nicely designed change, thank you very much.
BTW, the two first descriptions are swapped:

          "enum": [
            "Task Starts",
            "Task Progress",
            "Task Completes",
            "Task Errors",
            "Never"
          ],
          "enumDescriptions": [
            "When a task outputs progress (every message)",
            "When a task starts",
            "When a task finishes or errors",
            "When a task errors",
            "Never"
          ],

**Comment by nickdodd79** [comment]
That'll be the last minute change I did and clearly didn't check it all over. Thanks for the spot. I have released v1.3.1 with a correction.
