### ISSUE TITLE
does not support separated gulp tasks

### ISSUE THREAD

**Issue by kuntergunt** [nickdodd79/vscode-gulptasks#26]
I have split up my gulp tasks into multiple files in the ./gulp/tasks directory. The extension just says "no gulp files found".
(see http://macr.ae/article/splitting-gulpfile-multiple-files.html )

The gulpfile.js itself at minimum just looks like this (can have additional stuff like default task, watch etc.):
require('require-dir')('./gulp-tasks');

Is there a way to add support for this?

**Comment by nickdodd79** [comment]
Hi @kuntergunt 

In theory the file splitting should just work. The extension uses `gulp --tasks-simple` to get a list of tasks for given gulp file. It seems weird that gulp doesn't resolve the split out tasks when that is invoked, but does when a tasks is execute.

I will need to replicate the setup to see what is happening.

Nick.

**Comment by nickdodd79** [comment]
Hey @kuntergunt 

I finally found some time to look into this and don't seem to be able to replicate. When I split the tasks into separate files and use `require('require-dir')('./tasks');` to bring them together in a gulp file, it works.

![image](https://user-images.githubusercontent.com/28779139/48432013-55469f80-e7c7-11e8-9886-fb84de71452a.png)

![image](https://user-images.githubusercontent.com/28779139/48432058-714a4100-e7c7-11e8-8c21-738a57540574.png)

Looks like it is something in your local setup.

**Comment by nickdodd79** [comment]
Closing due to no follow up.
