### ISSUE TITLE
Define gulp task location?

### ISSUE THREAD

**Issue by Graloth** [nickdodd79/vscode-gulptasks#5]
Is it possible to define where the gulpfile.js is located? I'm working with a rather large project with multiple gulp files, but I only need to work on 1 of them.

**Comment by nickdodd79** [comment]
Hi @Graloth,

You sure can. Check out the "gulptasks.discovery.dir" setting in VS Code and see if that fulfils your needs (can be absolute or relative to the workspace root). 

If not, let me know and I can make some adjustments.

Nick.

**Comment by Graloth** [comment]
That did indeed work for me, is there a file which lists the available settings? Just so I can see if there are other things I might want to customize :)

**Comment by nickdodd79** [comment]
Awesomes. Glad it worked. 

You can see all the 'contributions' an extension provides on it's page in VS Code. Part of those contributions are it's settings. Here is a snip of what it should look like.

![image](https://user-images.githubusercontent.com/28779139/34868575-5f958ef4-f7d8-11e7-842a-589d45abb93e.png)

**Comment by Graloth** [comment]
Awesome, did not know that, thanks a lot!

**Comment by gilluminate** [comment]
I know this is closed, but I'd like to mention that giving an option for specifying the specific file location would be nice. For example, we have more than one in the same directory, so they obviously aren't both named "gulpfile.js" as this extension assumes. Or maybe even an option to specify a filename to look for in addition to the directory.

**Comment by nickdodd79** [comment]
Makes sense. I'll put something together.

**Comment by nickdodd79** [comment]
Hi,

This is in place now and will go with the next release. Got one more thing to add before I publish though so give it a few days.

Nick.

**Comment by nickdodd79** [comment]
Hi,

Version 0.0.9 that include a config option to specify a gulp file to load. If that can't be resolve it falls back to the normal discovery process.

Nick.
