### ISSUE TITLE
Restart task

### ISSUE THREAD

**Issue by pwsandoval** [nickdodd79/vscode-gulptasks#6]
I use Gulp with BrowserSync and when it has been disconnected due to some error in my code I try to execute the task again with the extension by clicking on the green icon and nothing happens.

I must finish the task and then run again, is there any way that it is automatic or a button that stops and re-executes the same task again (restart the same task)?

**Comment by nickdodd79** [comment]
Hi @pwsandoval,

There is a red stop icon used to terminate a gulp process - it terminates the process selected in the list. You can use that to stop the gulp task and then the green icon to start it again. Does that work for your scenario?

![image](https://user-images.githubusercontent.com/28779139/35023936-1969d5cc-fb91-11e7-9587-446816a1ffa3.png)

Nick.

**Comment by pwsandoval** [comment]
Yes, but I was referring to an option to restart it (stop and start in one step).

**Comment by nickdodd79** [comment]
Gotcha. I'm on it :-)

**Comment by nickdodd79** [comment]
Hi @pwsandoval, 

Version 0.0.9 has now been released and include a restart command, which will stop and start a task in a single action. An icon has been added to the extension navigation palette.

![image](https://user-images.githubusercontent.com/28779139/35182022-fcd9a616-fe20-11e7-8a81-85d2698b0d58.png)

Nick.

**Comment by pwsandoval** [comment]
Yes, excellent improvement.
