### ISSUE TITLE
make gulpfile.js discovery case insensitive

### ISSUE THREAD

**Issue by josephliccini** [nickdodd79/vscode-gulptasks#8]
our file was named `gulpFile.js` and this extensions wasn't able to discover it.

Thanks!
Joe

**Comment by nickdodd79** [comment]
Should be an easy fix. I'll get something out to you shortly.

**Comment by nickdodd79** [comment]
Hi @josephliccini 

I have just published version 0.0.10, which should hopefully address your case insensitive issue.

Nick.

**Comment by josephliccini** [comment]
awesome thanks!
